### PR TITLE
A bunch of updates/changes

### PR DESCRIPTION
**Pull request by OrganicIrradiation**
Most notable changes are changing the brewery beer information to a generator to deal with multi-page results, reorganising and adding more tests, updating the a number of fields for beers and breweries to integers/floats, and updated the README.md with the most recent output format.

The code could use some refactoring to make the code style for each of the functions consistent.  I am also thinking that a review generator should be returned by the rb.beer(url) function.  Would it be worthwhile considering moving these functions to classes (e.g., a Beer class and a Brewery class) to make the organisation of structures a bit cleaner?  This may be too much work for the payoff, but perhaps worth considering.

### CODE REVIEW

**Comment by alilja** [comment]
I'm going to begin refactoring and standardizing the code. Thanks for al your contributions!

**Comment by OrganicIrradiation** [comment]
Happy to help! I've been trying to see if I can parse anything interesting from some of the data in my free time; hence the modifications that have come-about from my testing.  I wanted to see if there were systematic biases to rate stronger beers higher, but the data is a bit too noisy at the moment (that is, no clear systematic biases, just more variability in ratings at the lower ABVs).

**Comment by alilja** [comment]
That's the best way to add stuff; it's how I've been adding things as well. 

I've made substantial changes and called this v2.0. Have a look and see if I missed anything.

**Comment by OrganicIrradiation** [comment]
Wow, tons of changes. Seems to be working well and you really did a great job of reorganising things. I'll make sure to note any issues that might come up.

**Pull request merged**
